---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    dnf:
      name: apache2
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    dnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "CentOS"  
